// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9hY_wtgXqUEfmbWCrR6gmlUhTObdtngc',
    appId: '1:207036575449:web:e04d6f67c1ced12d2798c8',
    messagingSenderId: '207036575449',
    projectId: 'borewell-guard',
    authDomain: 'borewell-guard.firebaseapp.com',
    databaseURL: 'https://borewell-guard-default-rtdb.firebaseio.com',
    storageBucket: 'borewell-guard.firebasestorage.app',
    measurementId: 'G-XX5KHGB9TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv3-0r_VMUL1Uxqs8ic3DV9VdqYE0YvLs',
    appId: '1:207036575449:android:248a640a652436962798c8',
    messagingSenderId: '207036575449',
    projectId: 'borewell-guard',
    databaseURL: 'https://borewell-guard-default-rtdb.firebaseio.com',
    storageBucket: 'borewell-guard.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNxODzAXJR1FhVKGcUJdLWjFUYrfUKZDw',
    appId: '1:207036575449:ios:c8f02dd4b5e3acae2798c8',
    messagingSenderId: '207036575449',
    projectId: 'borewell-guard',
    databaseURL: 'https://borewell-guard-default-rtdb.firebaseio.com',
    storageBucket: 'borewell-guard.firebasestorage.app',
    iosBundleId: 'com.example.borewellGuardApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNxODzAXJR1FhVKGcUJdLWjFUYrfUKZDw',
    appId: '1:207036575449:ios:c8f02dd4b5e3acae2798c8',
    messagingSenderId: '207036575449',
    projectId: 'borewell-guard',
    databaseURL: 'https://borewell-guard-default-rtdb.firebaseio.com',
    storageBucket: 'borewell-guard.firebasestorage.app',
    iosBundleId: 'com.example.borewellGuardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9hY_wtgXqUEfmbWCrR6gmlUhTObdtngc',
    appId: '1:207036575449:web:65a615afd97ac1642798c8',
    messagingSenderId: '207036575449',
    projectId: 'borewell-guard',
    authDomain: 'borewell-guard.firebaseapp.com',
    databaseURL: 'https://borewell-guard-default-rtdb.firebaseio.com',
    storageBucket: 'borewell-guard.firebasestorage.app',
    measurementId: 'G-HYVD1FB30Z',
  );
}
